/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'hsl(var(--primary))',
        'primary-600': 'hsl(var(--primary-600))',
        'primary-700': 'hsl(var(--primary-700))',
        accent: 'hsl(var(--accent))',
        success: 'hsl(var(--success))',
        warning: 'hsl(var(--warning))',
        danger: 'hsl(var(--danger))',
        bg: 'hsl(var(--bg))',
        'bg-2': 'hsl(var(--bg-2))',
        'bg-3': 'hsl(var(--bg-3))',
        fg: 'hsl(var(--fg))',
        'fg-2': 'hsl(var(--fg-2))',
        'fg-3': 'hsl(var(--fg-3))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        'sidebar-bg': 'hsl(var(--sidebar-bg))',
        'sidebar-fg': 'hsl(var(--sidebar-fg))',
        'sidebar-active-bg': 'hsl(var(--sidebar-active-bg))',
        'sidebar-active-fg': 'hsl(var(--sidebar-active-fg))',
        'navy-dark': '#001738',
        'navy-light': '#183B56',
        'accent-yellow': '#F7B84B',
        'highlight-peach': '#FBE5DC',
        'border-peach': '#E9C9BD',
        'bg-4': '#F0F3F8',
        'pill-gray': '#E3E6EC',
        'pill-green': "#CFE7D4",
        'pill-dark-green': "#095019",
        'orange': "#FF5F1F",
        'light-orange': "#FFDFD2",
        'dark-orange': "#CC4C19",
        'dark-blue': "#1A3E6D"
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
      },
      fontFamily: {
        sans: ['Inter','ui-sans-serif','system-ui','-apple-system','Segoe UI','Roboto','Arial','Noto Sans'],
      },
      fontSize: {
        xs: 'var(--fs-xs)',
        sm: 'var(--fs-sm)',
        base: 'var(--fs-md)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
      },
    },
  },
  plugins: [],
}